management:
  endpoints:
    web:
      exposure:
        include: '*'
#      path-mapping:
  #        health: salud
  endpoint:
    httptrace:
      enabled: true
      cache:
        time-to-live: 6000
    health:
      show-details: always
  trace:
    http:
      include: remote_address, parameters

info:
  app:
    name: Spring Actuator
    version: 1.0.0
    description: Simple app
