spring:
  h2:
    console:
      enabled: true

server:
  port: 8081
  servlet:
    context-path: /
  compression:
    enabled: true
  address: 0.0.0.0
management:
  endpoints:
    web:
      exposure:
        include: 'beans,health'

  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.transaction: TRACE
    org.springframework.data.r2dbc: TRACE